### ISSUE TITLE
EKU eats bonus energy

### ISSUE THREAD

**Issue by Crystark** [psouza4/EKUnleashed#1]
Hi Pete,

I'm not sure where you want us to report bugs now but since you're on github I thought this may now be the better place.

I just started using EKU for mid-night DIs (thanks for that !) and i noticed that the mid-night energy boost that usually makes me wake up with 70/50 energy wasn't there this morning. I think this may be because every hour the "spend energy" event pops up and triggers the energy boost. Or it may just be because you fetch on a regular basis the player data (and thus the current energy). Anyway, i was wondering if you could maybe add an option that forbids any action that might trigger the energy boost that we could switch on / off. I don't use any auto-maze or auto-explore feature so there really is no possibility for energy consumption.

Thanks for this great tool.

**Comment by psouza4** [comment]
I don't see how this is possible -- you have maybe misconfigured EK Unleashed and checked on the use of spending energy (maze towers or exploration).  EK Unleashed doesn't do anything automatic without you instructing it to.

**Comment by Crystark** [comment]
I'll do that once again tonight and get you the logs if you want but I have no automatism checked besides DI, thief and FoH spins

Would the checked "Fight treasure / fight monster" in the general settings cause this ? I see they were checked. Auto maze though isn't. I've unchecked those in case they cause trouble.

**Comment by Crystark** [comment]
Hi,

Here are tonight logs:

```
23:51 :: Looking for a thief to fight...
23:51 :: Switched to thief deck
23:51 :: [Notification]  You have new rewards available!
23:51 :: Thief battle won: 1 110 EXP, 1 660 gold
23:51 :: Switched back to default deck
00:04 :: Spending energy...
00:04 :: Switched to default deck to spend energy
00:59 :: [Notification]  You have new rewards available!
00:59 :: [Notification]  You have new rewards available!
01:04 :: Spending energy...
01:04 :: Switched to default deck to spend energy
01:50 :: Looking for a thief to fight...
01:50 :: Switched to thief deck
01:50 :: Thief battle won: 3 790 EXP, 5 690 gold
01:50 :: Switched back to default deck
02:04 :: Spending energy...
02:05 :: Switched to default deck to spend energy
03:05 :: Spending energy...
03:05 :: Switched to default deck to spend energy
04:05 :: Spending energy...
04:05 :: Switched to default deck to spend energy
05:00 :: [Notification]  You have new rewards available!
05:05 :: Spending energy...
05:05 :: Switched to default deck to spend energy
06:00 :: Now fighting the demon [Pazuzu||EKU||CARD||EKU||9008||EKU||0||EKU|| ] who has 536 000 000 HP...
06:00 :: Filled Demon Invasion deck (deck slot 10) with: 
06:00 :: ... filled deck 10 with:
06:00 :: Switched to demon invasion deck
06:00 :: Demon invasion battle result: 101 050 EXP, 151 580 gold, 1 010 589 merit
06:05 :: Spending energy...
06:05 :: Demon invasion battle result: 107 320 EXP, 160 980 gold, 1 073 251 merit
06:11 :: Demon invasion battle result: 89 850 EXP, 134 780 gold, 898 551 merit
06:17 :: Demon invasion battle result: 95 950 EXP, 143 930 gold, 959 560 merit
06:23 :: Demon invasion battle result: 107 770 EXP, 161 660 gold, 1 077 736 merit
06:28 :: Demon invasion battle result: 73 630 EXP, 110 440 gold, 736 324 merit
06:34 :: Demon invasion battle result: 118 610 EXP, 177 920 gold, 1 186 199 merit
06:40 :: Demon invasion battle result: 103 970 EXP, 155 960 gold, 1 039 735 merit
06:46 :: Demon invasion battle result: 91 070 EXP, 136 600 gold, 910 711 merit
06:51 :: Demon invasion battle result: 98 220 EXP, 147 330 gold, 982 216 merit
06:57 :: Demon invasion battle result: 100 820 EXP, 151 230 gold, 1 008 204 merit
07:03 :: Demon invasion battle result: 80 700 EXP, 121 050 gold, 807 037 merit
07:08 :: Demon invasion battle result: 90 680 EXP, 136 030 gold, 906 896 merit
07:14 :: Demon invasion battle result: 84 650 EXP, 126 980 gold, 846 544 merit
07:20 :: Demon invasion battle result: 107 740 EXP, 161 610 gold, 1 077 431 merit
07:24 :: [Notification]  You have new rewards available!
07:24 :: ... finished demon invasion; gained a total of 13 443 553 merit and finishing #5!
07:24 :: Switched back to default deck
07:24 :: Switched to default deck to spend energy
07:24 :: Switched to default deck
07:24 :: Switched to default deck
```

Once again this morning I was at 50/50 although over 7h past so i should be at 70 energy.

Automation has the following checked:
- Automate demon invasion
- Automate thief fights
- Automate field of honor 'happy hour' spins

Can something else be misconfigured ?
Thanks

**Comment by psouza4** [comment]
I think if you are above max energy, it spends it automatically so you
don't run the risk of losing energy due to cap.  That may not be something
you can configure.

Out of thousands of users, nobody's really brought it up so I think you're
using EK Unleashed in a way most people don't.  Is there a reason you don't
want EK Unleashed to use your over-capped energy?

On Thu, Nov 5, 2015 at 11:38 PM, Laurent notifications@github.com wrote:

> Hi,
> 
> Here are tonight logs:
> 
> 23:51 :: Looking for a thief to fight...
> 23:51 :: Switched to thief deck
> 23:51 :: [Notification]  You have new rewards available!
> 23:51 :: Thief battle won: 1 110 EXP, 1 660 gold
> 23:51 :: Switched back to default deck
> 00:04 :: Spending energy...
> 00:04 :: Switched to default deck to spend energy
> 00:59 :: [Notification]  You have new rewards available!
> 00:59 :: [Notification]  You have new rewards available!
> 01:04 :: Spending energy...
> 01:04 :: Switched to default deck to spend energy
> 01:50 :: Looking for a thief to fight...
> 01:50 :: Switched to thief deck
> 01:50 :: Thief battle won: 3 790 EXP, 5 690 gold
> 01:50 :: Switched back to default deck
> 02:04 :: Spending energy...
> 02:05 :: Switched to default deck to spend energy
> 03:05 :: Spending energy...
> 03:05 :: Switched to default deck to spend energy
> 04:05 :: Spending energy...
> 04:05 :: Switched to default deck to spend energy
> 05:00 :: [Notification]  You have new rewards available!
> 05:05 :: Spending energy...
> 05:05 :: Switched to default deck to spend energy
> 06:00 :: Now fighting the demon [Pazuzu||EKU||CARD||EKU||9008||EKU||0||EKU|| ] who has 536 000 000 HP...
> 06:00 :: Filled Demon Invasion deck (deck slot 10) with:
> 06:00 :: ... filled deck 10 with:
> 06:00 :: Switched to demon invasion deck
> 06:00 :: Demon invasion battle result: 101 050 EXP, 151 580 gold, 1 010 589 merit
> 06:05 :: Spending energy...
> 06:05 :: Demon invasion battle result: 107 320 EXP, 160 980 gold, 1 073 251 merit
> 06:11 :: Demon invasion battle result: 89 850 EXP, 134 780 gold, 898 551 merit
> 06:17 :: Demon invasion battle result: 95 950 EXP, 143 930 gold, 959 560 merit
> 06:23 :: Demon invasion battle result: 107 770 EXP, 161 660 gold, 1 077 736 merit
> 06:28 :: Demon invasion battle result: 73 630 EXP, 110 440 gold, 736 324 merit
> 06:34 :: Demon invasion battle result: 118 610 EXP, 177 920 gold, 1 186 199 merit
> 06:40 :: Demon invasion battle result: 103 970 EXP, 155 960 gold, 1 039 735 merit
> 06:46 :: Demon invasion battle result: 91 070 EXP, 136 600 gold, 910 711 merit
> 06:51 :: Demon invasion battle result: 98 220 EXP, 147 330 gold, 982 216 merit
> 06:57 :: Demon invasion battle result: 100 820 EXP, 151 230 gold, 1 008 204 merit
> 07:03 :: Demon invasion battle result: 80 700 EXP, 121 050 gold, 807 037 merit
> 07:08 :: Demon invasion battle result: 90 680 EXP, 136 030 gold, 906 896 merit
> 07:14 :: Demon invasion battle result: 84 650 EXP, 126 980 gold, 846 544 merit
> 07:20 :: Demon invasion battle result: 107 740 EXP, 161 610 gold, 1 077 431 merit
> 07:24 :: [Notification]  You have new rewards available!
> 07:24 :: ... finished demon invasion; gained a total of 13 443 553 merit and finishing #5!
> 07:24 :: Switched back to default deck
> 07:24 :: Switched to default deck to spend energy
> 07:24 :: Switched to default deck
> 07:24 :: Switched to default deck
> 
> Once again this morning I was at 50/50 although over 7h past so i should
> be at 70 energy.
> 
> Automation has the following checked:
> - Automate demon invasion
> - Automate thief fights
> - Automate field of honor 'happy hour' spins
> 
> Can something else be misconfigured ?
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/psouza4/EKUnleashed/issues/1#issuecomment-154326423.

## 

-Pete

**Comment by Crystark** [comment]
So what happens when i reach 50 energy and I haven't checked any energy-using automation ? Am I loosing energy or is EKU consuming it anyways ?

Here's what was my goal in this usage:
For instance during the maze event I want to use all my energy on mazes but never kill the last stage's monsters. As EKU doesn't seem to support that (but maybe it does ?) i want the night's energy to stack up so that when I wake up i'm at 70 and can use it to clear the mazes manually before the reset.

You probably know about it but since a recent upgrade they force you to clear a stage (kill all chests and monsters) before advancing to the next so the only energy savings you can do on maze events now are the last stage monsters (2 to 6 energy saved per maze).

Maybe I'm not asking the right thing. Maybe what I need to ask is that EKU handles the new restrictions on maze clearing ?

Thanks for your help on the matter.

**Comment by freeWilly77** [comment]
That is normal. If you are playing the game it can't get over 50.
It only reaches 70 if you do nothing in game. Means no di, thiefs etc
