### ISSUE TITLE
Bulk Card Selling Tool does not respect locked cards

### ISSUE THREAD

**Issue by fyreflow** [psouza4/EKUnleashed#12]
After testing with one-star cards, I have confirmed that the bulk selling tool will respect enchanted cards, but not locked ones.  Which for me, means that I cannot use it on my two-star and three-star collections. Most of the cards I want to keep there are locked but not enchanted. Quite a few of these cards were limited release and not generally available, so losing them would be quite a drawback (for certain FoH criteria, to name one example).

Yes, I know I could enchant all of them to level 1, but... that would be onerous. I have been a big fan of the card lock feature ever since it was first introduced, and I would like to see EKU take every card's locked/unlocked property value into consideration with any feature that involves feeding/selling cards.

**Comment by psouza4** [comment]
Will be resolved in the next release.

**Comment by fyreflow** [comment]
Just thought I'd let you know that I tested it with v2.11.2416.1050, and it's still selling my level 0 locked cards.

**Comment by psouza4** [comment]
Locks may or may not be set correctly and also you can't lock them in the
mobile app while EKU is running since the data isn't saved with the cards.
For more details and troubleshooting, try the Debug tab to check lock data.
