### ISSUE TITLE
EKU stopping from lv131 on

### ISSUE THREAD

**Issue by guibalzary** [psouza4/EKUnleashed#17]
Eku is acting oddly after lv130 gets past.
My xp bar and other data at left pane does not show up anymore, and sometimes it stops doing some things, like arena battles.

I thank you for the client, in advance.

**Comment by Crystark** [comment]
+1 seems to be an int vs long problem.

**Comment by psouza4** [comment]
This is exactly what I said in group chat and proposed someone fix it and submit a pull request.  I've stopped playing this game and stopped officially supporting EK Unleashed.  I will accept pull requests and make new installers for it though.

**Comment by Crystark** [comment]
I understand, it still is an open issue though :)
Peppa made a fix for it and it's waiting as a pull request :)
