### ISSUE TITLE
New to Github/ EKU Update Help

### ISSUE THREAD

**Issue by zs0** [psouza4/EKUnleashed#4]
Avid EKU user here, I would very much like to keep my EKU client updated since the transition to open source.

I see there have been "5 commits" as of this post, which appear to be new additions and/or bug fixes to EKU. However, the EKU .exe file that is available for download has the same version name, and doesn't appear to contain anything new. Is this correct?

If anyone would mind terribly to help me understand how to update my EKU client, I would greatly appreciate it.

**Comment by psouza4** [comment]
The commits I accepted yesterday are code changes that have not been built
into a binary (.exe) yet.  You may build a new version yourself or wait
until I get around to doing so -- I don't build new releases the instant a
commit comes through ;)

On Tue, Nov 10, 2015 at 6:23 PM, zs0 notifications@github.com wrote:

> Avid EKU user here, I would very much like to keep my EKU client updated
> since the transition to open source.
> 
> I see there have been "5 commits" as of this post, which appear to be new
> additions and/or bug fixes to EKU. However, the EKU .exe file that is
> available for download has the same version name, and doesn't appear to
> contain anything new. Is this correct?
> 
> If anyone would mind terribly to help me understand how to update my EKU
> client, I would greatly appreciate it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/psouza4/EKUnleashed/issues/4.

## 

-Pete

**Comment by GammieP** [comment]
the new build fr9om what it looks like seem to enable deck selection for DI. One feature i am most looking forward to. How does someone go about "Building a new version" themselves ?

**Comment by zs0** [comment]
Thanks Pete, that explanation is helpful. But yes, like GammieP asks in addition, is there any way you can advise building a binary .exe using the files provided here? Is it a difficult task or relatively simple? Do I need specific software, or a large knowledge of coding? I'd love to learn something new and take a whack at it. Thanks.

**Comment by psouza4** [comment]
It's not a short answer and there's plenty of tutorials on how to build a project from github out there, however it may be moot for you anyway since these changes are available in the 2.05 release.
